//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public class Debt
{
	public float original_debt_sum{get;set;}
	public float left_tb_payed{get;set;}									//variable to keep track of amount left to be payed per debt
	public float monthly_cut{get;set;}										//variable to keep track of monthly cut per debt (default value = 1000)
	public float interest_percent{get;set;}									//variable to keep track of interest percentage upon taking up a new debt
	public float interest{get;set;}											//variable to keep track of interest value per debt
	public float debt_payment{get;set;}										//variable to keep track of debt payment per debt

	public bool active{get;set;}											//variable to keep track of debt's active state

	public Debt()															//constructor that initializes variables
	{
		original_debt_sum = 0.0f;
		left_tb_payed = 0.0f;
		monthly_cut = 0.0f;

		active = false;
	}
	
	//function that calculates interest per debt
	//called each time a new debt is taken
	public void CalcInterest()
	{
		interest = (interest_percent) * left_tb_payed;
	}
	
	//function to calculate debt payment per debt
	//called each time a new debt is taken but after all the necessary calculations have been performed
	//ie calculate interest percent and interest
	public void CalcDebtPayment()
	{
		debt_payment = monthly_cut + interest;
	}

	//function to calculate the monthly cut for each debt
	public void CalcMonthlyCut()
	{
		monthly_cut = original_debt_sum * 0.05f;
	}
}

public class FinanceManager
{
	public PlayerObjData Player{get;set;}									//access the Player's data
	public List<Debt> listofdebts{get;set;}									//store all the debts taken
	
	public int days_till_update{get;set;}									//variable to keep track of the number of days until the next update (default value = 30)
	private int debt_max;													//variable for the maximum number of debts the Player can take
	
	public float player_money{get;set;}										//variable to keep track of the amount of money the player has at the given moment
	public float payment_total{get;set;}									//variable to store the sum of all the debts
	public float existing_cash{get;set;}									//variable to keep track the resultant amount after minusing payment total from player money
		
	public bool day_pass{get;set;}											//variable set to true only if a day has passed

	public float default_percent{get;set;}									//variable contributing to calculating interest percentage
	public float increase_percent{get;set;}									//variable contributing to calculating interest percentage

	public int month{get;set;}												//variable to keep track of months (required in the calculation of interest percent)

	public FinanceManager()
	{
	}

	public FinanceManager (PlayerObjData player)							//constructor that initializes variables, takes in a PlayerObjData
	{
		Player = player;
		listofdebts = new List<Debt>();
		
		days_till_update = 30;
		debt_max = 3;
		
		payment_total = 0.0f;
				
		day_pass = false;
		default_percent = 0.05f;
		increase_percent = 0.05f;

		//adding debt_max amount of Debts to the list
		for(int i = 0; i < debt_max; i++)
		{
			listofdebts.Add(new Debt());
		}

		month = 1;
	}
	
	//function taht updates the Player's amount of money after paying off the debts
	public void UpdatePlayerMoney()
	{
		player_money = Player.Money;
	}
	
	//function that calculates the Player's existing cash
	public void CalcExistingCash()
	{
		existing_cash = (int)(player_money - payment_total);
	}
	
	//function to calculate the new interest percentage each time Player takes on a new debt
	public void CalcInterestPercent()
	{				
		//as long as there is a debt, calculate interest percentage for the particular debt
		for(int i = 0; i < listofdebts.Count; i++)
		{
			if(listofdebts[i] != null)
			{
				listofdebts[i].interest_percent = (increase_percent * month) + default_percent;
			}
		}
	}
	
	//function to calculate the sum of all debt payments upon taking up new debt
	public void CalcPaymentTotal(bool traverse)
	{
		//as long as ther is debt
		if(listofdebts.Count > 0)
		{
			if(!traverse)
			{
				payment_total += listofdebts[listofdebts.Count - 1].debt_payment;
			}
			else
			{
				//traverse through the debt payments of each debt and add it to payment total
				for(int i = 0; i < listofdebts.Count; i++)
				{
					payment_total += listofdebts[i].debt_payment;
				}
			}
		}
	}
	
	//function to update the number of days until the next update
	public void UpdateDays()
	{
		//as long as a day has passed, decrease the number of days until next update
		if(day_pass)
		{
			days_till_update--;

			//once, number of days are used up for the month, increase month value, update the necessary values and reset the value for the number of days
			if(days_till_update <= 0)
			{
				month++;
				UpdateValues();
				days_till_update = 30;
			}
			day_pass = false;
		}
	}

	//function to update values upon click of shorten debt button and upon update of month
	public void UpdateValues()
	{
		//update interest percents, interests, debt payments of each debt and peyment total
		CalcInterestPercent();
		
		for(int i = 0; i < listofdebts.Count; i++)
		{
			listofdebts[i].CalcInterest();
			listofdebts[i].CalcDebtPayment();
		}

		//reset payment total and recalculate value of payment total
		payment_total = 0.0f;
		CalcPaymentTotal(true);
		CalcExistingCash();
	}
	
	//function for Player to take on a new debt
	//assign new debt into specific index
	//set debt to active
	public void AddDebt(int index)
	{
		listofdebts[index] = new Debt();
		listofdebts[index].active = true;
	}
}