using UnityEngine;
using System.Collections.Generic;

[System.Serializable]
public class InvBaseItem
{
	public enum Type
	{
		None,
		LightWeapon,
		HeavyWeapon,
		Utility,
		_Amount
	}

	/// <summary>
	/// 16-bit item ID, generated by the system.
	/// Not to be confused with a 32-bit item ID, which actually contains the ID of the database as its prefix.
	/// </summary>

	public int id16;
	
	public string name;
	public string description;
	public Type type = Type.None;

	public int minItemLevel = 1;
	public int maxItemLevel = 10;

	/// <summary>
	/// And and all base stats this item may have at a maximum level.
	/// Actual object's stats are calculated based on item's level and quality.
	/// </summary>

	public List<InvStat> stats = new List<InvStat>();

	/// <summary>
	/// Game Object that will be created and attached to the specified slot on the body.
	/// This should typically be a prefab with a renderer component, such as a sword,
	/// a bracer, shield, etc.
	/// </summary>

	public GameObject attachment;

	public Color color = Color.white;
	public UIAtlas iconAtlas;
	public string iconName = "";
}